services:
  backend:
    image: danieii/crypto-stack-backend
    ports:
      - "8000:8000"
    volumes:
      - "./backend:/app"

  frontend:
    image: danieii/crypto-stack-frontend
    ports:
      - "5173:5173"
    volumes:
      - "./frontend/src:/app/src"
      - "./frontend/index.html:/app/index.html"
