services:
  backend:
    image: crypto-stack-backend
    ports:
      - "8000:8000"
    volumes:
      - "./backend:/app"

  frontend:
    image: crypto-stack-frontend
    ports:
      - "5173:5173"
    volumes:
      - "./frontend:/app"
