# Generated by Django 4.2.3 on 2024-01-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_coin_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='api_key',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
