# Generated by Django 4.2.3 on 2024-01-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_alter_wallet_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='api_key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
