# Generated by Django 4.2.3 on 2024-01-14 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0004_alter_wallet_api_key'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coin',
        ),
    ]
