# Generated by Django 4.2.3 on 2024-02-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0005_delete_coin'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='api_secret',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
